# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshmanager" do
  version "2.7.0"

  on_macos do
    on_arm do
      sha256 "d6f3ddd42fc73d2664118d683f82af24e87d75883a53ac6a8111ef37dba94758"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "23a003ce1d25e6c2f7aa0d5c43000c8a357ba16ee08fa6435009eaf4cf9d58f1"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8ed829ffbff49bb8851d865d9bd2b2a22786c4f1e7a7cfb0902ca0b09777b1f1"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c72396c27be24172217117e5268f76d78e5a4c6deda6872208b4229732dd44f1"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Linux_x86_64.tar.gz"
    end
  end

  name "sshmanager"
  desc "Simple SSH manager CLI tool."
  homepage "https://github.com/emirhangumus/sshmanager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshmanager"

  # No zap stanza required
end
