# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshmanager" do
  version "2.6.0"

  on_macos do
    on_arm do
      sha256 "ebf418505bde1932ccbb3e38aa0a80423331b6f1c58447075fc976342962e22c"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d92b3ce3f01ae785edc3279628b80b7d1895d2c056a68acac0fcc204c4632ab"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bb183169c7b01499ddb94ef52fe0ecd1cbbb48a2c06cbf9124fa3db25cc56a1a"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c28a31444a3541576f81d571cf3065aa7d98bca99b9d26985797e7f54b8e54fc"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Linux_x86_64.tar.gz"
    end
  end

  name "sshmanager"
  desc "Simple SSH manager CLI tool."
  homepage "https://github.com/emirhangumus/sshmanager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshmanager"

  # No zap stanza required
end
