# This file was generated by GoReleaser. DO NOT EDIT.
cask "sshmanager" do
  version "2.3.1"

  on_macos do
    on_intel do
      sha256 "5ce96443565908544b83eefeb549dc74173dfcc7d30e2d6004cc91cf122918fa"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "924919dec78f9061dc9c00f6fdb272f498d9ad1e62616aedc28971daf36d98ab"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa016b779392d88932655bb8c2bfd7fcb7c63dfd588111bd8a7519a5bd8137a9"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "750f150380ca9009133b05b51b09803f5d3cc5c3b251147dd670a3f810ef7b29"
      url "https://github.com/emirhangumus/sshmanager/releases/download/v#{version}/sshmanager_Linux_arm64.tar.gz"
    end
  end

  name "sshmanager"
  desc "Simple SSH manager CLI tool."
  homepage "https://github.com/emirhangumus/sshmanager"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sshmanager"

  # No zap stanza required

end
